add compile-check and warning as err

diff --git a/.github/workflows/unit-test-bestla.yml b/.github/workflows/unit-test-bestla.yml
--- a/.github/workflows/unit-test-bestla.yml
+++ b/.github/workflows/unit-test-bestla.yml
@@ -53,6 +53,9 @@ jobs:
 
       - name: Check Result
         run: |
+          if [[ $(grep -c "No such file or directory" ${{ github.workspace }}/bestla/build/unit_test_bestla.log) != 0 ]]; then
+            echo "neural-speed Compile Failed"
+            exit 1
           if [[ $(grep -c "Case Failed" ${{ github.workspace }}/bestla/build/unit_test_bestla.log) != 0 ]]; then
             echo "UT Failed! Please check UT log."
             exit 1
